package cmd

import (
	"errors"
)

// errUnexpected - unexpected error, requires manual intervention.
var errUnexpected = errors.New("Unexpected error, please report this issue at https://github.com/minio/minio/issues")

// errFileNotFound - cannot find the file.
var errFileNotFound = errors.New("file not found")

// errFileNameTooLong - given file name is too long than supported length.
var errFileNameTooLong = errors.New("file name too long")

// errFileAccessDenied - cannot access file, insufficient permissions.
var errFileAccessDenied = errors.New("file access denied")

// VerifyFileError represents error generated by VerifyFile posix call.
type VerifyFileError string

// Error method for the hashMismatchError
func (h VerifyFileError) Error() string {
	return string(h)
}
